name: 'Auto merge 3rd party'

# Controls when the action will run.
on:
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-20.04
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@f81beb99aef41bb55ad072857d43073fba833a98"
        env:
          GITHUB_TOKEN: "${{ secrets.MY_TOKEN }}"
          MERGE_LABELS: "automerge,3rdparty"
          MERGE_METHOD: rebase
          UPDATE_LABELS: "automerge,3rdparty"
          UPDATE_METHOD: rebase
