name: 'Test action'

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Any text'
        # Default value if no value is explicitly provided
        default: 'World'
        required: false
  # schedule:
  #   - cron: '0 0 * * 6' # Run on Saturday

jobs:
  Update3rdParty:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Test hub
    #   run: hub --version
      # env:
      #   GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

    # - name: Test gh
    #   run: gh --version
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
    - name: Install dependencies
      run: yarn

    # - name: Linting and build scripts
    #   run: yarn build:scripts

    # - name: Run 3rd party update
    #   run: node dist/scripts/update-3rd-party.js

    # - name: Test
    #   id: changes
    #   uses: UnicornGlobal/has-changes-action@v1.0.11

    # - name: Print status 2
    #   run: |
    #     git status
    #     echo "${{steps.changes.outputs.changed}}"
    #     git add .
    #     echo "${{steps.changes.outputs.changed}}"
    #     git status

    # - name: Create Pull Request
    #   if: steps.changes.outputs.changed == 1
    #   uses: peter-evans/create-pull-request@v3.1.0
    #   with:
    #     commit-message: 'Chore: Update 3rd party'
    #     branch: "create-pull-request/run-${{ github.run_id }}-${{ github.run_number}}"
    #     draft: false
    #     title: '[Action] Update 3rd party'
    #     labels:  "automerge"
    #     token: "${{ secrets.MY_TOKEN }}"


