# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Any text'
        # Default value if no value is explicitly provided
        default: 'World'
        required: false
  schedule:
    - cron: '0 0 * * 6' # Run on Saturday

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: yarn

    - name: Linting and build scripts
      run: yarn build:scripts

    - name: Run 3rd party update
      run: node dist/scripts/update-3rd-party.js

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'Chore: Update 3rd party'
        branch: create-pull-request/test
        assignees: sarvaje
        draft: false
        title: '[Action] Update 3rd party'
        labels: automerge
